### ISSUE TITLE
Add progression information when downloading

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#7]
Right now we don't have any feedback when downloading a new version: the size, the bandwidth etc. Could be good to have at least those info. A progress bar would be nice too if possible.

**Comment by aubincleme** [comment]
Currently looking at options for that. The biggest problem here is that if we add a third party library for displaying a progress bar / for doing nice graphics, then it will significantly increase the complexity of the install for a user.

**Comment by surli** [comment]
>  then it will significantly increase the complexity of the install for a user.

if we put the dependencies in a requirements.txt and the install just need to run `pip install -r requirements.txt` I don't think it's that much complexity :)

**Comment by aubincleme** [comment]
I'd like to limit the need to do that actually : 
* If you have to do simply `apt install package1 package2`, then it's fine
* If you have to use `pip` and install packages that are not bundled for standard package managers then it's a bit harder
  * My current understanding is that we should prefer using `virtualenv` / `venv` instead of directly using `pip` without virtual environment : when using `pip` without venv, the downloaded python packages are stored in the home directory of the user, and can then interfere with other python packages that the user has installed locally. 
  * If we use venv, this involves more hassle for the end user, which has to install and setup the venv by himself, so the installation is more difficult
  * Still in the case of a venv, we need to make sure that the venv is sourced before running xtool
  * However, having a venv would enable us the possibility to port xtool to more platforms (not only the ones with `apt` as a package manager)

**Comment by aubincleme** [comment]
@surli after rethinking this, I'm starting to believe that if we don't choose to add other libraries to the tool, we'll quickly run out of possibilities … thus I'll try to see how we can do an install as easy as possible while allowing the install of pip packages.

**Comment by surli** [comment]
> if we don't choose to add other libraries to the tool, we'll quickly run out of possibilities …

Agreed :)

**Comment by aubincleme** [comment]
Will try to include tqdm progress bar in the download of XWiki versions

**Comment by aubincleme** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/5938943/69652159-81029380-1071-11ea-9c5f-b639be752fd6.png">

Not that bad IMO ; committing it if it works well …
